export default {
  "date": "日期",
  "media_id": '投放媒体',
  "corp_id": '投放公司',
  "xiao_hao_jin_e": '消耗金额',
  "you_xiao_zhu_ce_ren_shu": '有效注册人数',
  "zong_zhuan_hua_lv": '总转化率',
  "ri_ROI": '日ROI',
  "dang_ri_xin_zeng_fu_fei_ren_shu": '当日新增付费人数',
  "dang_ri_xin_zeng_fu_fei_jin_e": '当日新增付费金额',
  "dang_ri_xin_zeng_ARPPU": '当日新增ARPPU',
  "zhu_ce_cheng_ben": '注册成本',
  "dan_fu_fei_yong_hu_cheng_ben": '单付费用户成本',
  "zhu_ce_qie_liao_tian_ren_shu": '注册且聊天人数',
  "liao_tian_lv": '聊天率',
  "fu_fei_ren_shu": '付费人数',
  "fu_fei_jin_e": '付费金额',
  "nan_xing_fu_fei_zhuan_hua_lv": '男性付费转化率',
  "ji_huo_shu": '激活数',
  "zhu_ce_zong_shu": '注册总数',
  "deng_lu_lv": '登录率',
  "nan_xing_zhu_ce_ren_shu": '男性注册人数',
  "nv_xing_zhu_ce_ren_shu": '女性注册人数',
  "wu_xing_bie_zhu_ce_ren_shu": '无性别注册人数',
  "ci_ri_liu_cun_lv": '次日留存率',
  "3_ri_liu_cun_lv": '3日留存率',
  "7_ri_liu_cun_lv": '7日留存率'
}